apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-producer
  namespace: iot-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-producer
  template:
    metadata:
      labels:
        app: iot-producer
    spec:
      containers:
      - name: iot-producer
        image: sheep-producer:latest
        imagePullPolicy: Never  

        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-headless.kafka.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "iot-sensor-data"
        - name: PRODUCER_INTERVAL
          value: "1" 
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
